### ISSUE TITLE
port na aplikacje do esx_phone

### ISSUE THREAD

**Issue by majormarcin** [majormarcin/FiveM_ESX_Roleplay_PL#7]
[esx_phone oddzielnie](https://github.com/majormarcin/esx_phone/projects/1)
- [ ] aplikacja Twitter to samo co #4 
- [ ] aplikacja grupowa (gangi)

**Comment by deviljin112** [comment]
Prosciej zrobic apki wbudowane w telefon i zrobic na zasadzie eden_darknet (patrz testowy) ze kupujesz chip zeby apka byla widoczna i dzialala w telefonie, np. GPS zeby miec GPS'a... itp

**Comment by majormarcin** [comment]
- [ ] aplikacja Twitter to samo co #4 
- [ ] aplikacja grupowa (gangi)

**Comment by majormarcin** [comment]
porzucony
